import Image from 'next/image'

const Articles = () => {
  return (
    <div className="relative pb-[200px]">
      <div className="container relative z-10 flex flex-col items-center justify-center gap-10 xl:flex-row">
        <div className="flex flex-col gap-8">
          <div className="article-box">
            <Image
              src="/static/images/landing/articles/01.svg"
              alt="img"
              width={190}
              height={160}
              className="w-[190px] h-[160px] rounded-lg"
            />
            <div className="flex flex-col">
              <h1 className="text-xl font-medium text-transparent bg-gradient-to-r from-outrageous-orange-500 to-festival-500 bg-clip-text">
                veFNX Voters
              </h1>
              <p className="text-sm text-white">veFNX lockers get 100% of the revenue generated by the protocol.</p>
            </div>
          </div>
          <div className="article-box">
            <Image
              src="/static/images/landing/articles/02.svg"
              alt="img"
              width={190}
              height={160}
              className="w-[190px] h-[160px] rounded-lg"
            />
            <div className="flex flex-col">
              <h1 className="text-xl font-medium text-transparent bg-gradient-to-r from-outrageous-orange-500 to-festival-500 bg-clip-text">
                Trader
              </h1>
              <p className="text-sm text-white">
                We offer Spot Traders the best DeFi experience by providing a comprehensive user interface, and offering
                a variety of strategies such as Dollar Cost Averaging (DCA), Limit/Range Orders, Recurrent Buys, and
                Cross-Chain Bridging.
              </p>
            </div>
          </div>
          <div className="article-box">
            <Image
              src="/static/images/landing/articles/03.svg"
              alt="img"
              width={190}
              height={160}
              className="w-[190px] h-[160px] rounded-lg"
            />
            <div className="flex flex-col">
              <h1 className="text-xl font-medium text-transparent bg-gradient-to-r from-outrageous-orange-500 to-festival-500 bg-clip-text">
                Protocols
              </h1>
              <p className="text-sm text-white">
                Deposit bribe incentives to your liquidity pools to attract veFNX votes and emissions that will drive
                protocol liquidity at the lowest possible cost.
              </p>
            </div>
          </div>
        </div>
        <div className="article-big-box">
          <h1 className="mb-3 text-xl font-medium text-transparent bg-gradient-to-r from-outrageous-orange-500 to-festival-500 bg-clip-text">
            Liquidity Providers
          </h1>
          <p className="mb-10 text-sm text-white">
            We provide Liquidity Providers (LPs) with the best Concentrated Liquidity (CL) user experience by offering a
            wide range of strategies. Our platform supports automatic CL Management (CLMs) for novices and manual,
            pre-selected ranges for more experienced users.
            <br />
            <br />
            Additionally, LPs can directly set their ranges from within the chart in our user interface, simplifying the
            process for all.
            <br />
            <br />
            We also feature dynamic fees to reduce Impermanent Loss (IL) and an emissions distributor algorithm that
            rewards fees generated, enhancing overall user satisfaction and financial outcomes.
          </p>
          <div className="w-full h-[360px">
            <Image
              src="/static/images/landing/articles/04.svg"
              alt="img"
              width={600}
              height={300}
              className="w-full h-full rounded-lg"
            />
          </div>
        </div>
      </div>
      <Image
        src="/static/images/landing/articles/world.png"
        alt="img"
        width={600}
        height={300}
        className="w-full h-[60%] rounded-lg absolute bottom-[-10px]"
      />
    </div>
  )
}

export default Articles
